# three ways to use this file (in recommended order):
# - copy <this-file> to docker-compose.override.yml and customize it
# - docker compose -f docker-compose.yml -f <this-file>
# - merge this file into docker-compose.yml
version: '3.5'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      # store raw database files
      - db-data:/var/lib/postgresql/data
      # place database initialization *.sql and *.sql.gz file here
      - ${PWD}/db-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data:
